"use client";
import Link from "next/link";
import { ChangeEvent, DragEvent, useEffect, useState } from "react";

type KDoc={title:string;filename:string;steps:number;images:number};
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";

export default function KnowledgeBasePage(){
 const [docs,setDocs]=useState<KDoc[]>([]),[file,setFile]=useState<File|null>(null);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[drag,setDrag]=useState(false);
 const [error,setError]=useState(""),[success,setSuccess]=useState<KDoc|null>(null);
 async function refresh(){setLoading(true);try{const r=await fetch(`${api}/api/v1/knowledge/documents?refresh=${Date.now()}`,{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.detail);setDocs(p.documents??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load Knowledge Base") }finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 function choose(value?:File){setSuccess(null);setError("");if(!value)return setFile(null);if(!value.name.toLowerCase().endsWith(".docx")){setFile(null);setError("Please select a Microsoft Word DOCX document.");return}setFile(value)}
 function drop(e:DragEvent<HTMLLabelElement>){e.preventDefault();setDrag(false);choose(e.dataTransfer.files?.[0])}
 async function upload(){if(!file||busy)return;setBusy(true);setError("");const form=new FormData();form.append("file",file);try{const r=await fetch(`${api}/api/v1/knowledge/documents`,{method:"POST",body:form});const p=await r.json();if(!r.ok)throw new Error(p.detail);setSuccess(p);setFile(null);await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to index document")}finally{setBusy(false)}}
 return <div className="app-shell"><aside className="sidebar"><Link className="side-logo" href="/"><img src="/glazed-mind-logo.png" alt="GlazedMind"/><span>GLAZED<br/><b>MIND</b></span></Link><nav><Link href="/"><span>{"\u2302"}</span><span>Workspace</span></Link><Link href="/onboarding"><span>{"\u25A3"}</span><span>Onboarding</span></Link><Link href="/support"><span>{"\u2726"}</span><span>Customer Portal</span></Link><Link href="/chatbot"><span>{"\u25C8"}</span><span>Chatbot</span></Link><Link className="active" href="/knowledge-base"><span>{"\u25A4"}</span><span>Knowledge Base</span></Link><Link href="/escalations"><span>{"\u2667"}</span><span>Escalations</span></Link><Link href="/impact"><span>{"\u25C9"}</span><span>Impact</span></Link></nav><div className="side-note"><b>Dynamic Knowledge</b><small>DOCX + pgvector</small></div></aside>
 <main className="dashboard knowledge-dashboard"><header><div className="top-brand"><img src="/glazed-mind-logo.png" alt=""/><div><strong>GlazedMind</strong><small>Knowledge Base management · Help Desk workspace</small></div></div><div className="connection"><span/>pgvector connected</div></header>
 <section className="knowledge-hero"><div><p className="eyebrow">Dynamic knowledge management</p><h1>Teach GlazedMind<br/><em>new procedures.</em></h1><p>Upload a verified DOCX runbook. Its steps, screenshots, and embedding become available to Workspace and Chatbot immediately.</p></div><div className="knowledge-stat"><b>{docs.length}</b><span>indexed guides</span><small>{docs.reduce((n,d)=>n+d.steps,0)} structured entries</small></div></section>
 <section className="knowledge-layout"><article className="upload-panel"><div className="card-heading"><div><p className="eyebrow">Add documentation</p><h2>Upload a DOCX guide</h2></div><span className="grounded-pill">Incremental indexing</span></div><label className={`docx-dropzone${drag?" dragging":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop}><input type="file" accept=".docx" onChange={(e:ChangeEvent<HTMLInputElement>)=>choose(e.target.files?.[0])}/><span className="upload-icon">⇧</span><b>{file?.name??"Drop your DOCX here"}</b><small>{file?`${(file.size/1048576).toFixed(2)} MB · Ready to index`:"or click to choose a verified Word document"}</small></label><div className="upload-notes"><span>✓ Steps remain in document order</span><span>✓ Embedded screenshots stay attached</span><span>✓ Same filename safely updates the guide</span></div><button className="index-button" onClick={()=>void upload()} disabled={!file||busy}>{busy?"Extracting, embedding & indexing…":"Add to Knowledge Base →"}</button>{error&&<p className="upload-error">{error}</p>}{success&&<div className="upload-success"><b>Document indexed successfully</b><p>{success.title}</p><span>{success.steps} entries · {success.images} screenshots · Available now</span></div>}</article>
 <article className="catalog-panel"><div className="card-heading"><div><p className="eyebrow">Verified sources</p><h2>Indexed documents</h2></div><button className="catalog-refresh" onClick={()=>void refresh()} disabled={loading}>{loading?"Loading…":"Refresh"}</button></div><div className="document-list">{loading&&!docs.length?<div className="catalog-empty">Reading the Knowledge Base…</div>:docs.map(d=><div className="document-row" key={d.filename}><span className="document-icon">W</span><div><b>{d.title}</b><small>{d.filename}</small></div><div className="document-metrics"><span>{d.steps} entries</span><span>{d.images} images</span></div></div>)}</div></article></section>
 <section className="ingestion-flow">{[["01","DOCX Upload","Permanent verified source"],["02","Structure Extraction","Steps and screenshots"],["03","Vector Index","nomic-embed-text + pgvector"],["04","Ready for Agents","Workspace and Chatbot"]].map((x,i)=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small>{i<3&&<i>→</i>}</div>)}</section><footer>THINK SWEET. &nbsp; SOLVE SMART.</footer></main></div>
}
